### ISSUE TITLE
Improper outputs on asking basic question to csv file

### ISSUE THREAD

**Issue by akshaytheau** [hardbyte/qabot#15]
I tested the titanic csv file ask question functionality. It worked fine for the question "How many men were onboard the titanic ?" with a customLLM error.

But for all the other questions asked , it is not working properly. Questions asked.

1) How many females are there in the dataset ?
2) Tell me some insights about the csv data.
3) What is the row count of the dataset ?

**Comment by hardbyte** [comment]
Should be way better now after upgrading to use openai's function api directly.
