### ISSUE TITLE
Wiki Data

### ISSUE THREAD

**Issue by bluusun** [hardbyte/qabot#6]
Not sure if feasible but that would be a great source!

https://query.wikidata.org/

**Comment by hardbyte** [comment]
It would certainly be feasible, chatGPT-4 at least can generate valid SPARQL queries.

With the request: "Generate a SPARQL query to run on Wikidata for the question "What are the largest cities in the world that have a female mayor?""

![image](https://user-images.githubusercontent.com/855189/229267562-b0fe6bb9-3a1a-4b9b-a3e3-20d60466627a.png)

![image](https://user-images.githubusercontent.com/855189/229267568-c392c9d4-f0a7-4ba0-b09f-5ca9a66988b6.png)

I'll consider adding it to `qabot`

**Comment by hardbyte** [comment]
Ok it worked first try so I guess I'll include that :-)


```
Query: What are the largest cities in the world that have a female mayor?
```json
{
    "action": "wikidata",
    "action_input": "SELECT ?city ?cityLabel ?population ?mayor ?mayorLabel WHERE { ?city wdt:P31 wd:Q515; wdt:P1082 ?population; wdt:P6 ?mayor. ?mayor wdt:P21 wd:Q6581072. SERVICE wikibase:label { 
bd:serviceParam wikibase:language '[AUTO_LANGUAGE],en'. } } ORDER BY DESC(?population) LIMIT 10"
}
```
The largest cities in the world with a female mayor are: 1. Mumbai, India with Kishori Pednekar as mayor (population: 15,414,288); 2. Harbin, China with Sun Zhe as mayor (population: 10,009,854); 3. 
Mexico City, Mexico with Claudia Sheinbaum as mayor (population: 9,209,944); 4. Johannesburg, South Africa with Mpho Phalatse as mayor (population: 4,434,827); 5. Los Angeles, United States with 
Karen Bass as mayor (population: 3,898,747); 6. Casablanca, Morocco with Nabila Rmili as mayor (population: 3,499,000); 7. Taichung, Taiwan with Lu Shiow-yen as mayor (population: 3,033,885); 8. 
Guayaquil, Ecuador with Cynthia Viteri as mayor (population: 2,723,665); 9. Lusaka, Zambia with Chilando Chitangala as mayor (population: 2,467,563); 10. Caracas, Venezuela with Helen Fernández as 
mayor (population: 2,245,744).

    wikidata
      SELECT ?city ?cityLabel ?population ?mayor ?mayorLabel WHERE { ?city wdt:P31 wd:Q515; wdt:P1082 ?population; wdt:P6 ?mayor. ?mayor wdt:P21 wd:Q6581072. SERVICE wikibase:label { bd:serviceParam 
wikibase:language '[AUTO_LANGUAGE],en'. } } ORDER BY DESC(?population) LIMIT 10

      {'head': {'vars': ['city', 'cityLabel', 'population', 'mayor', 'mayorLabel']}, 'results': {'bindings': [{'city': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q1156'}, 'mayor': 
{'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q76174641'}, 'population': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'type': 'literal', 'value': '15414288'}, 'cityLabel': 
{'xml:lang': 'en', 'type': 'literal', 'value': 'Mumbai'}, 'mayorLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Kishori Pednekar'}}, {'city': {'type': 'uri', 'value': 
'http://www.wikidata.org/entity/Q42956'}, 'mayor': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q9126496'}, 'population': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'type': 
'literal', 'value': '10009854'}, 'cityLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Harbin'}, 'mayorLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Sun Zhe'}}, {'city': {'type': 
'uri', 'value': 'http://www.wikidata.org/entity/Q1489'}, 'mayor': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q5771800'}, 'population': {'datatype': 
'http://www.w3.org/2001/XMLSchema#decimal', 'type': 'literal', 'value': '9209944'}, 'cityLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Mexico City'}, 'mayorLabel': {'xml:lang': 'en', 
'type': 'literal', 'value': 'Claudia Sheinbaum'}}, {'city': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q34647'}, 'mayor': {'type': 'uri', 'value': 
'http://www.wikidata.org/entity/Q109682887'}, 'population': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'type': 'literal', 'value': '4434827'}, 'cityLabel': {'xml:lang': 'en', 'type': 
'literal', 'value': 'Johannesburg'}, 'mayorLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Mpho Phalatse'}}, {'city': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q65'}, 'mayor': 
{'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q461739'}, 'population': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'type': 'literal', 'value': '3898747'}, 'cityLabel': 
{'xml:lang': 'en', 'type': 'literal', 'value': 'Los Angeles'}, 'mayorLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Karen Bass'}}, {'city': {'type': 'uri', 'value': 
'http://www.wikidata.org/entity/Q7903'}, 'mayor': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q108699304'}, 'population': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'type':
'literal', 'value': '3499000'}, 'cityLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Casablanca'}, 'mayorLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Nabila Rmili'}}, {'city': 
{'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q245023'}, 'mayor': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q8274707'}, 'population': {'datatype': 
'http://www.w3.org/2001/XMLSchema#decimal', 'type': 'literal', 'value': '3033885'}, 'cityLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Taichung'}, 'mayorLabel': {'xml:lang': 'en', 'type': 
'literal', 'value': 'Lu Shiow-yen'}}, {'city': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q43509'}, 'mayor': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q3008822'}, 
'population': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'type': 'literal', 'value': '2723665'}, 'cityLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Guayaquil'}, 'mayorLabel': 
{'xml:lang': 'en', 'type': 'literal', 'value': 'Cynthia Viteri'}}, {'city': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q3881'}, 'mayor': {'type': 'uri', 'value': 
'http://www.wikidata.org/entity/Q112195612'}, 'population': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'type': 'literal', 'value': '2467563'}, 'cityLabel': {'xml:lang': 'en', 'type': 
'literal', 'value': 'Lusaka'}, 'mayorLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Chilando Chitangala'}}, {'city': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q1533'}, 
'mayor': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q21573102'}, 'population': {'datatype': 'http://www.w3.org/2001/XMLSchema#decimal', 'type': 'literal', 'value': '2245744'}, 
'cityLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Caracas'}, 'mayorLabel': {'xml:lang': 'en', 'type': 'literal', 'value': 'Helen Fernández'}}]}}
  
        

    


Total tokens 3435 approximate cost $0.00687


Result:
The largest cities in the world with a female mayor are: 1. Mumbai, India with Kishori Pednekar as mayor (population: 15,414,288); 2. Harbin, China with Sun Zhe as mayor (population: 10,009,854); 3. 
Mexico City, Mexico with Claudia Sheinbaum as mayor (population: 9,209,944); 4. Johannesburg, South Africa with Mpho Phalatse as mayor (population: 4,434,827); 5. Los Angeles, United States with 
Karen Bass as mayor (population: 3,898,747); 6. Casablanca, Morocco with Nabila Rmili as mayor (population: 3,499,000); 7. Taichung, Taiwan with Lu Shiow-yen as mayor (population: 3,033,885); 8. 
Guayaquil, Ecuador with Cynthia Viteri as mayor (population: 2,723,665); 9. Lusaka, Zambia with Chilando Chitangala as mayor (population: 2,467,563); 10. Caracas, Venezuela with Helen Fernández as 
mayor (population: 2,245,744).

```

**Comment by bluusun** [comment]
Wow this looks awesome!
