### ISSUE TITLE
Longer input files/pdfs

### ISSUE THREAD

**Issue by bluusun** [hardbyte/qabot#7]
Is there an option (maybe it already exists) to use input material longer than 4k tokens?

**Comment by hardbyte** [comment]
Fitting more than 4k tokens is the entire point of qabot using a database. You can happily connect to and query multi-GiB datasets already.

I don't think this tool should deal with embedding or parsing other formats just to keep the dependencies to a minimum. I'd like to keep this focused on querying tabular data.

**Comment by bluusun** [comment]
Indeed - why do I get an error message when using a CSV that's 4.6k tokens?
